version: '3.8'

services:
  discourse:
    image: discourse/discourse:latest
    container_name: discourse_local
    restart: unless-stopped
    ports:
      - "3000:80"  # Changed from 80 to avoid permission issues
      - "3001:443" # Changed from 443 to avoid permission issues
    environment:
      - DISCOURSE_HOSTNAME=localhost:3000
      - DISCOURSE_DEVELOPER_EMAILS=admin@localhost
      - DISCOURSE_SMTP_ADDRESS=localhost
      - DISCOURSE_SMTP_PORT=25
      - DISCOURSE_SMTP_USER_NAME=
      - DISCOURSE_SMTP_PASSWORD=
      - DISCOURSE_SMTP_ENABLE_START_TLS=false
      - DISCOURSE_SMTP_DOMAIN=localhost
      - DISCOURSE_DB_HOST=postgres
      - DISCOURSE_DB_NAME=discourse
      - DISCOURSE_DB_USERNAME=discourse
      - DISCOURSE_DB_PASSWORD=discourse_local_password
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PASSWORD=redis_local_password
      - DISCOURSE_SECRET_KEY_BASE=local_secret_key_for_testing_only_change_in_production_1234567890abcdef
      - DISCOURSE_CDN_URL=
      - DISCOURSE_S3_ENDPOINT=
      - DISCOURSE_S3_ACCESS_KEY_ID=
      - DISCOURSE_S3_SECRET_ACCESS_KEY=
      - DISCOURSE_S3_BUCKET=
      - DISCOURSE_S3_REGION=
      - DISCOURSE_S3_CDN_URL=
      - DISCOURSE_S3_INSTALL_CORS_RULES=true
      - DISCOURSE_S3_UPLOAD_BUCKET=
      - DISCOURSE_S3_BACKUP_BUCKET=
      - DISCOURSE_S3_MIGRATE_TO_S3=true
      # Local testing specific settings
      - DISCOURSE_DEVELOPER_EMAILS=admin@localhost
      - DISCOURSE_SMTP_DISABLE=true
      - DISCOURSE_SMTP_ADDRESS=localhost
      - DISCOURSE_SMTP_PORT=25
      - DISCOURSE_SMTP_USER_NAME=
      - DISCOURSE_SMTP_PASSWORD=
      - DISCOURSE_SMTP_ENABLE_START_TLS=false
      - DISCOURSE_SMTP_DOMAIN=localhost
      # Fix for migration issues
      - DISCOURSE_DB_POOL=5
      - DISCOURSE_DB_TIMEOUT=5000
      - DISCOURSE_DB_STATEMENT_TIMEOUT=10000
    depends_on:
      - postgres
      - redis
    volumes:
      - discourse_data:/var/discourse
      - discourse_uploads:/var/discourse/shared/standalone/uploads
      - discourse_backups:/var/discourse/shared/standalone/backups

  postgres:
    image: pgvector/pgvector:pg15
    container_name: discourse_postgres_local
    restart: unless-stopped
    environment:
      - POSTGRES_DB=discourse
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=discourse_local_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflicts
    command: postgres -c shared_preload_libraries=vector

  redis:
    image: redis:6-alpine
    container_name: discourse_redis_local
    restart: unless-stopped
    command: redis-server --requirepass redis_local_password
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"  # Changed from 6379 to avoid conflicts

volumes:
  discourse_data:
  discourse_uploads:
  discourse_backups:
  postgres_data:
  redis_data:
